In [156]:
# !pip install tqdm
# !pip install time

ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time


# 00. PyTorch Fundamentals



## What is PyTorch?


PyTorch is an open source machine learning and deep learning framework.


# What can PyTorch be used for?

PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.


## Who uses PyTorch?

Many of the worlds largest technology companies such as Meta (Facebook), Tesla and Microsoft as well as artificial intelligence research companies such as OpenAI use PyTorch to power research and bring machine learning to their products.



For example, Andrej Karpathy (head of AI at Tesla) has given several talks (PyTorch DevCon 2019, Tesla AI Day 2021) about how Tesla use PyTorch to power their self-driving computer vision models.

PyTorch is also used in other industries such as argiculture to power computer vision on tractors.


## Why use PyTorch?

Machine learning researchers love using PyTorch. And as of February 2022, PyTorch is the most used deep learning framework on Papers With Code, a website for tracking machine learning research papers and the code repositories attached with them.



PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.


And if companies such as Tesla and Meta (Facebook) use it to build models they deploy to power hundreds of applications, drive thousands of cars and deliver content to billions of people, it's clearly capable on the development front too.


# What we're going to cover in this module

This course is broken down into different sections (notebooks).

Each notebook covers important ideas and concepts within PyTorch.

Subsequent notebooks build upon knowledge from the previous one (numbering starts at 00, 01, 02 and goes to whatever it ends up going to).

This notebook deals with the basic building block of machine learning and deep learning, the tensor.

Specifically, we're going to cover:


# Where can can you get help?
All of the materials for this course live on GitHub.

And if you run into trouble, you can ask a question on the Discussions page there too.

There's also the PyTorch developer forums, a very helpful place for all things PyTorch.

# Importing PyTorch

Note: Before running any of the code in this notebook, you should have gone through the PyTorch setup steps.

However, if you're running on Google Colab, everything should work (Google Colab comes with PyTorch and other libraries installed).

Let's start by importing PyTorch and checking the version we're using.


In [222]:
import torch
import numpy as pd
import pandas as pd
from tqdm import tqdm
import time
import matplotlib.pyplot as plt
print(torch.__version__)

1.9.1+cpu


Wonderful, it looks like we've got PyTorch 1.10.0 (as of Decemeber 2021). This means if you're going through these materials, you'll see most compatability with PyTorch 1.10.0, however if your version number is far higher than that, you might notice some inconsistencies.

And if you do have any issues, please post on the GitHub Discussions page.

# Introduction to tensors

Now we've got PyTorch imported, it's time to learn about tensors.

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

In [158]:
# Scalar
scalar = torch.tensor(10)
scalar

tensor(10)

See how the above printed out tensor(7)?

That means although scalar is a single number, it's of type torch.Tensor.

We can check the dimensions of a tensor using the ndim attribute.

In [159]:
scalar.ndim

0

What if we wanted to retrieve the number from the tensor?

As in, turn it from torch.Tensor to a Python integer?

To do we can use the item() method.

In [160]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

10

Okay, now let's see a vector.

A vector is a single dimension tensor but can contain many numbers.

As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

The important trend here is that a vector is flexible in what it can represent (the same with tensors).

In [161]:
# Vector
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

Wonderful, vector now contains two 7's, my favourite number.

How many dimensions do you think it'll have?

In [162]:
# Check the number of dimensions of vector
vector.ndim

1

In [163]:
# Check shape of vector
vector.shape

torch.Size([2])

The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

Let's now see a matrix.

In [164]:
# Matrix
MATRIX = torch.tensor([[10, 8], 
                       [12, 10]])
MATRIX

tensor([[10,  8],
        [12, 10]])

Wow! More numbers! Matrices are as flexible as vectors, except they've got an extra dimension.

In [165]:
MATRIX[0]

tensor([10,  8])

In [169]:
MATRIX[1]

tensor([12, 10])

In [170]:
# Check number of dimensions
MATRIX.ndim

2

MATRIX has two dimensions (did you count the number of square brakcets on the outside of one side?).

What shape do you think it will have?

In [171]:
MATRIX.shape

torch.Size([2, 2])

We get the output torch.Size([2, 2]) because MATRIX is two elements deep and two elements wide.

How about we create a tensor?

In [172]:
# Tensor
TENSOR = torch.tensor([[[5, 9, 7],
                        [4, 8, 10],
                        [11, 12, 15]]])
TENSOR

tensor([[[ 5,  9,  7],
         [ 4,  8, 10],
         [11, 12, 15]]])

In [173]:
TENSOR[0]

tensor([[ 5,  9,  7],
        [ 4,  8, 10],
        [11, 12, 15]])

In [174]:
TENSOR.ndim

3

And what about its shape?

In [175]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Alright, it outputs torch.Size([1, 3, 3]).

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

# Random tensors

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tenors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...


As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using torch.rand() and passing in the size parameter.

In [176]:
# Create a random tensor of size (3, 4)

random_tensor =torch.rand(size=(3, 4))
random_tensor,random_tensor.dtype

(tensor([[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]),
 torch.float32)

In [177]:
random_tensor.ndim

2

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of




[224, 224, 3] ([height, width, color_channels]).


In [178]:
#creat arandom of size(224,224, 3)
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and ones


Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the size parameter comes into play.

In [179]:
zeros = torch.zeros(size=(5, 6))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones except using torch.ones() instead.

In [180]:
ones = torch.ones(size=(5, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [181]:
random_tensor.dtype

torch.float32

# Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

1.start = start of range (e.g. 0)

2.end = end of range (e.g. 10)

3.step = how many steps in between each value (e.g. 1)


**Note**: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.


In [182]:
# Use torch.arang
torch.arange(1 , 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
# Use torch.arange(), torch.range() is deprecated 

zero_to_ten_deprecated = torch.arange(0, 10) # Note: this may return an error
zero_to_ten = torch.arange(start=1, end=12, step=1)

zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.


For example, a tensor of all zeros with the same shape as a previous tensor.



To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [184]:

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [185]:
ten_zeros = torch.ones_like(input=zero_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers

Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [186]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 8.0, 10.0],
                              dtype = None, # defaults to None, which is t
                               device= None, # defaults to None, which us
                              requires_grad = False) # if True, operations perfromed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

In [187]:
float_16_tensor = torch.tensor([3.0, 8.0, 10.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [188]:
float_16_tensor.dtype

torch.float16

In [189]:
float_16_tensor * float_32_tensor

tensor([  9.,  64., 100.])

In [190]:
int_32_tensor = torch.tensor([3, 8, 10],dtype=torch.int32)
int_32_tensor

tensor([ 3,  8, 10], dtype=torch.int32)

In [191]:
float_32_tensor * int_32_tensor

tensor([  9.,  64., 100.])

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

**shape** - what shape is the tensor? (some operations require specific shape rules)

**dtype** - what datatype are the elements within the tensor stored in?

**device** - what device is the tensor stored on? (usually GPU or CPU)

In [192]:
#Creat a tensor
some_tensor = torch.rand(5, 6)
# finde out datails about it
print(some_tensor)
      
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Device tensor is stord on :{some_tensor.device}")

tensor([[0.9536, 0.6002, 0.0351, 0.6826, 0.3743, 0.5220],
        [0.1336, 0.9666, 0.9754, 0.8474, 0.8988, 0.1105],
        [0.4563, 0.9719, 0.3968, 0.1496, 0.4743, 0.9973],
        [0.4436, 0.9726, 0.5194, 0.5337, 0.7050, 0.3362],
        [0.7891, 0.1694, 0.1800, 0.7177, 0.6988, 0.5510]])
Shape of tensor:torch.Size([5, 6])
Datatype of tensor:torch.float32
Device tensor is stord on :cpu


**Note**: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error

# Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.



These operations are often a wonderful dance between:

**.**Addition

**.**Substraction

**.**Multiplication (element-wise)

**.**Division

**.**Matrix multiplication


And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).



Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [193]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2 , 3]) #start , end, step
tensor + 15

tensor([16, 17, 18])

In [194]:
# Multiply it by 10
tensor * 15

tensor([15, 30, 45])

In [195]:
tensor

tensor([1, 2, 3])

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [196]:
# Tensors don't change unless reassigned
tensor = tensor - 15
tensor

tensor([-14, -13, -12])

In [197]:
tensor = tensor + 10
tensor

tensor([-4, -3, -2])

PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplcation) and torch.add() to perform basic operations.

In [198]:
# Can also use torch functions
torch.multiply(tensor, 15)

tensor([-60, -45, -30])

In [199]:
# Original tensor is still unchanged 
tensor

tensor([-4, -3, -2])

In [200]:
# Element-wise multiplication (each element multiplies its equivalent, index
print(tensor, "*",tensor)
print("Equals:",tensor * tensor)

tensor([-4, -3, -2]) * tensor([-4, -3, -2])
Equals: tensor([16,  9,  4])


# Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:


1-The inner dimensions must match:
(4, 3) @ (4, 3) won't work

(4, 3) @ (4, 3) will work

(4, 3) @ (4 ,3) will work

2-0The resulting matrix has the shape of the outer dimensions:

(4, 3) @ (4, 3) -> (4, 3)

(4, 3) @ (4, 3) -> (4, 3)

**Note**: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [201]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [202]:
# Element-wise matrix mutlication
tensor * tensor

tensor([1, 4, 9])

In [203]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [204]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)


You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [205]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value



Wall time: 999 µs


tensor(14)

In [206]:
%%time
torch.matmul(tensor, tensor)

Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [207]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[2, 3],
                         [5, 4],
                         [6, 7]], dtype=torch.float32)

tensor_B = torch.tensor([[8, 11],
                         [9, 12], 
                         [10, 13]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose.
Let's try the latter.

In [208]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[2., 3.],
        [5., 4.],
        [6., 7.]])
tensor([[ 8., 11.],
        [ 9., 12.],
        [10., 13.]])


In [209]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[2., 3.],
        [5., 4.],
        [6., 7.]])
tensor([[ 8.,  9., 10.],
        [11., 12., 13.]])


In [210]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 49.,  54.,  59.],
        [ 84.,  93., 102.],
        [125., 138., 151.]])

Output shape: torch.Size([3, 3])


You can also use torch.mm() which is a short for torch.matmul().

In [211]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A,tensor_B.T)

tensor([[ 49.,  54.,  59.],
        [ 84.,  93., 102.],
        [125., 138., 151.]])

Without the transpose, the rules of matrix mulitplication aren't fulfilled and we get an error like above.

How about a visual?

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
Note: You might also often see W or another letter like X used to showcase the weights matrix.
b is the bias term used to slightly offset the weights and inputs.
y is the output (a manipulation of the input in the hopes to discover patterns in it).
This is a linear function (you may have seen something like 
y
=
m
x
+
b
 in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of in_features and out_features below and see what happens.

Do you notice anything to do with the shapes?

In [212]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This  uses matrix mutlipaction
linear = torch.nn.Linear(in_features=2,
                        out_features = 6)

x = tensor_A
output = linear(x)
print(f"In put shape:{x.shape}\n")
print(f"output :\n{x.shape}\n")
print(f"output :{output}\n\noutput shape:{output.shape}")

In put shape:torch.Size([3, 2])

output :
torch.Size([3, 2])

output :tensor([[ 3.3644,  1.7131,  0.4592,  0.4575,  0.2355,  1.7308],
        [ 5.5731,  1.8657,  0.1371, -0.1600,  1.5868,  3.7070],
        [ 7.8744,  3.6487,  0.4102,  0.7415,  0.6539,  4.7186]],
       grad_fn=<AddmmBackward>)

output shape:torch.Size([3, 6])


Question: What happens if you change in_features from 2 to 3 above? Does it error? How could you change the shape of the input (x) to accomodate to the error? Hint: what did we have to do to tensor_B above?

If you've never done it before, matrix multiplication can be a confusing topic at first.

But after you've played around with it a few times and even cracked open a few neural networks, you'll notice it's everywhere.

Remember, matrix multiplication is all you need.

When you start digging into neural network layers and building your own, you'll find matrix multiplications everywhere. Source: https://marksaroufim.substack.com/p/working-class-deep-learner

Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [213]:
x = torch.arange(0, 200, 10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190])


Now let's perform some aggregation.

In [214]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 190
Mean: 95.0
Sum: 1900


**Note**: You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with torch methods.

In [215]:
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(190), tensor(0), tensor(95.), tensor(1900))

## Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [216]:
tensor = torch.arange(10.,200., 10.)
print(f"Tensor:{tensor}")

#Return index of max min values
print(f"Index where max value occurs:{tensor.argmax()}")
print(f"Index where  min value occures:{tensor.argmin()}")

Tensor:tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.,
        130., 140., 150., 160., 170., 180., 190.])
Index where max value occurs:18
Index where  min value occures:0



Now we'll create another tensor the same as before but change its datatype to torch.float16.

In [217]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.,
        130., 140., 150., 160., 170., 180., 190.], dtype=torch.float16)


And we can do something similar to make a torch.int8 tensor.

In [218]:
# Create a int8 tensor
tensor_int16 = tensor.type(torch.int16)
tensor_int16

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
        150, 160, 170, 180, 190], dtype=torch.int16)

In [219]:
tensor_complex_64 = tensor.type(torch.complex64)
tensor_complex_64

tensor([ 10.+0.j,  20.+0.j,  30.+0.j,  40.+0.j,  50.+0.j,  60.+0.j,  70.+0.j,  80.+0.j,  90.+0.j,
        100.+0.j, 110.+0.j, 120.+0.j, 130.+0.j, 140.+0.j, 150.+0.j, 160.+0.j, 170.+0.j, 180.+0.j,
        190.+0.j])

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

In [224]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [248]:
#Change view (keeps same data as original but changes view)
z = x.view(1, 9)
z , z.shape

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Now let's add an extra dimension with torch.reshape().

In [249]:
# Add an extra dimesion
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [250]:
# Changing z changes x
z[:, 0] = 9

z, x

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

In [251]:
x_stacked = torch.stack([x, x, x, x],dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [252]:
x_stacked = torch.stack([x, x, x, x],dim=1) #If dim=1, the matrix is horizontal and each number is repeated four times in a list.
x_stacked

tensor([[9., 9., 9., 9.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

To do so you can use torch.squeeze()..squeeze() can compress the matrix, 

and if the matrix is[50, 10, 1], for example, it will remove the 1 numbers

in the list and have the radiation of 1.

In [253]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [259]:
print(f"Previous tensor:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

##Add an extradimension with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor:tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor: tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [265]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 4))
# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) #shifts axis->1, 1-->2, 2->0
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 4])
New shape:torch.Size([4, 224, 224])


**Note**: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.


## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [287]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [293]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1



You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [294]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [295]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [298]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 2, 2]

tensor([9])

In [303]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 

x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (visualize, visualize, visualize), you'll start to get the hang of it.

# PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are

**.** torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

**.** torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

Let's try them out.

In [317]:
# Numpy array to tensor
import numpy as np
import torch
array  = np.arange(2.0, 9.0)
tensor = torch.from_numpy(array)
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

**Note**: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

Because we reassigned tensor above, if you change the tensor, the array stays the same.

In [318]:
# vhange the array keep the tensor
array = array + 1
array , tensor


(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))


And if you want to go from PyTorch tensor to NumPy array, you can call tensor.numpy().

In [319]:
# Tensor to NumPy array
tensor = torch.ones(8)  # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

And the same rule applies as above, if you change the original tensor, the new numpy_tensor stays the same.

In [320]:
# Change the tensor, keep the array the same

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?


So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [328]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(4, 5)
random_tensor_B = torch.rand(4, 5)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.9013, 0.2200, 0.2092, 0.5863, 0.3711],
        [0.1194, 0.9520, 0.3380, 0.8562, 0.2414],
        [0.7828, 0.1275, 0.9743, 0.4585, 0.0891],
        [0.2092, 0.0775, 0.3148, 0.9239, 0.6690]])

Tensor B:
tensor([[0.6238, 0.3573, 0.2736, 0.3706, 0.3284],
        [0.1624, 0.6632, 0.0646, 0.1315, 0.0823],
        [0.5463, 0.5446, 0.9853, 0.7523, 0.5578],
        [0.8626, 0.2615, 0.1565, 0.1150, 0.5195]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

In [337]:
import torch
import random
# # Set the random seed
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(4, 5)
# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
random_tensor_D = torch.rand(4, 5) # try commenting this line out and seeing what happens

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Dose Tensor C equal Tensor D?(any where)")

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274]])

Tensor D:
tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]])

Dose Tensor C equal Tensor D?(any where)


It looks like setting the seed worked.

**Resource**: What we've just covered only scratches the surface of reproducibility in PyTorch. For more, on reproducbility in general and random seeds, I'd checkout


The PyTorch reproducibility documentation (a good exericse would be to read through this for 10-minutes and even if you don't understand it now, being aware of it is important).
The Wikipedia random seed page (this'll give a good overview of random seeds and pseudorandomness in general).


### Running tensors on GPUs (and making faster computations)


Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

Note: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified

In [340]:
# Check for GPU
import torch
torch.cuda.is_available()

False


If the above outputs True, PyTorch can see and use the GPU, if it outputs False, it can't see the GPU and in that case, you'll have to go back through the installation steps.

Now, let's say you wanted to setup your code so it ran on CPU or the GPU if it was available.
That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a device variable to store what kind of device is available.


In [342]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

If the above output "cuda" it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output "cpu", our PyTorch code will stick with the CPU.

**Note**: In PyTorch, it's best practice to write device agnostic code. This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using torch.cuda.device_count().

In [343]:
#Count number of devices
torch.cuda.device_count()

0

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).


## 3. Putting tensors (and models) on the GPU
You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our device agnostic code (see above), it'll run on the CPU.


**Note**: Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)

Let's try creating a tensor and putting it on the GPU (if it's available).


In [345]:
# Create tensor default on cpu
tensor = torch.tensor([4, 5, 6])
# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([4, 5, 6]) cpu


tensor([4, 5, 6])

If you have a GPU available, the above code will output something like:

Notice the second tensor has device='cuda:0', this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'cuda:0' and 'cuda:1' respectively, up to 'cuda:n').


# 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the torch.Tensor.numpy() method on our tensor_on_gpu.

In [347]:
# If tensor is on CPU, can transform it to NumPy 
tensor_on_gpu.numpy()

array([4, 5, 6], dtype=int64)

Instead, to get a tensor back to CPU and usable with NumPy we can use Tensor.cpu().

This copies the tensor to CPU memory so it's usable with CPUs.

In [351]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([4, 5, 6], dtype=int64)

The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

In [352]:
tensor_on_gpu

tensor([4, 5, 6])

# Exercises

All of the exercises are focused on practicing the code above.

ou should be able to complete them by referencing each section or by following the resource(s) linked.

**Resources:**

Exercise template notebook for 00.
Example solutions notebook for 00 (try the exercises before looking at this).

Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

Create a random tensor with shape (7, 7).

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may
have to transpose the second tensor).

Set the random seed to 0 and do exercises 2 & 3 over again.
Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

Find the maximum and minimum values of the output of 7.

Find the maximum and minimum index values of the output of 7.

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 

Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.